### ISSUE TITLE
Cannot configure interpreter correctly 

### ISSUE THREAD

**Issue by juanradiego** [flathub/com.jetbrains.PyCharm-Community#89] opened 2020-06-01 11:38 UTC
Hi!

I am trying to use a pyenv and a pipenv inside the Flatpak Pycharm, just like in the local Pycharm.

First, I configured the base interpreter with the pyenv version from the host :

![image](https://user-images.githubusercontent.com/4417093/83404531-1b6dd600-a40b-11ea-89ce-4b08edb0e08d.png)

but I've realized that not even the python console runs properly:

```
/opt/pyenv/versions/3.8.3/bin/python /app/pycharm/plugins/python-ce/helpers/pydev/pydevconsole.py --mode=client --port=35017
/opt/pyenv/versions/3.8.3/bin/python: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory
Process finished with exit code 127
```
and on the host:
```
$ ldd /opt/pyenv/versions/3.8.3/bin/python 
        linux-vdso.so.1 (0x00007ffef0d33000)
        libcrypt.so.2 => /lib64/libcrypt.so.2 (0x00007f9353416000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f93533f5000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f93533ef000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f93533ea000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f93532a4000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f93530de000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9353481000)
```

The pyenv it's installed in /opt to be shared between users and works fine in user shell and the PyCharm version installed with the Jetbrains Toolbox.

Some system info (Fedora 30):
```
$ uname -a
Linux HOSTNAME 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

Is there something I am missing?

Thank you for your work!

**Comment by baudm** [comment] 2020-06-21 18:29
Essentially a duplicate of #14. See my comment there for the workaround.

**Closed** 2022-05-04 08:22 UTC
