### ISSUE TITLE
[0728/061237.950373:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/pycharm/jbr/lib/chrome-sandbox is owned by root and has mode 4755.

### ISSUE THREAD

**Issue by RajrupDasid** [flathub/com.jetbrains.PyCharm-Community#545] opened 2023-07-28 00:52 UTC
Please send some patches or tell us any work around to mitigate  crashing issue - when ever running or simply try to open a file .
Error log is ->
```
[0728/061237.950373:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /app/pycharm/jbr/lib/chrome-sandbox is owned by root and has mode 4755. 
```
Os details ->
OS - Pop-os 22.04 LTS  (updated).
flatpak version - Flatpak 1.14.4

**Comment by jdingbat** [comment] 2023-07-28 04:53
I am experiencing the same issue, oddly it only happens when I attempt to open certain files.

**Comment by FakeShemp** [comment] 2023-07-28 09:53
duplicate of #542

**Closed by FakeShemp** 2023-07-28 09:53 UTC
